name: restuarant_pager_app
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

# environment:
#   sdk: ^3.5.1
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^17.0.0
  firebase_messaging: ^14.7.20
  firebase_core: ^2.32.0
  flutter_lints: ^4.0.0
  google_fonts: ^6.1.0
  get: ^4.6.6
  intl: ^0.18.0
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.10+1
  pinput: ^5.0.0
  image_picker: ^1.1.2
  delightful_toast: ^1.1.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  google_sign_in: ^6.2.1
  firebase_storage: ^11.7.7
  path: ^1.9.0
  firebase_app_check: ^0.2.2+7
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  

flutter:
  uses-material-design: true

  
  assets:
    - assets/onboardingImg/
    - assets/images/
    - assets/phoneNumberAssets/
    - assets/loginAssets/
    - assets/signUpAssets/
    - assets/splashScreenImg/

  

 

