name: restuarant_pager_app
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

# environment:
#   sdk: ^3.5.1
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^17.0.0
  firebase_messaging: ^14.7.20
  firebase_core: ^2.27.1
  flutter_lints: ^4.0.0
  google_fonts: ^6.1.0
  get: ^4.6.6
  intl: ^0.18.0
  shared_preferences: ^2.2.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  

flutter:
  uses-material-design: true

  
  assets:
    - assets/onboardingImg/

  

 
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
 
