// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFTyOMor3T7iLJFs0DWhr8YPAEndCZqSo',
    appId: '1:163216286673:web:08d1b4e6495ec4e77ab6f0',
    messagingSenderId: '163216286673',
    projectId: 'restuarantpager',
    authDomain: 'restuarantpager.firebaseapp.com',
    databaseURL: 'https://restuarantpager-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'restuarantpager.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgW0Ue-GUIXhoVb5UPXaMrWt_cTlrsrOk',
    appId: '1:163216286673:android:32ad41afdc0e181c7ab6f0',
    messagingSenderId: '163216286673',
    projectId: 'restuarantpager',
    databaseURL: 'https://restuarantpager-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'restuarantpager.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvvTMwDekPtSmczAoVvd9_Hw7ZBT2a45A',
    appId: '1:163216286673:ios:48ed312934bb84977ab6f0',
    messagingSenderId: '163216286673',
    projectId: 'restuarantpager',
    databaseURL: 'https://restuarantpager-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'restuarantpager.appspot.com',
    iosBundleId: 'com.example.restuarantPagerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvvTMwDekPtSmczAoVvd9_Hw7ZBT2a45A',
    appId: '1:163216286673:ios:48ed312934bb84977ab6f0',
    messagingSenderId: '163216286673',
    projectId: 'restuarantpager',
    databaseURL: 'https://restuarantpager-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'restuarantpager.appspot.com',
    iosBundleId: 'com.example.restuarantPagerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFTyOMor3T7iLJFs0DWhr8YPAEndCZqSo',
    appId: '1:163216286673:web:7f2b57ef695210ad7ab6f0',
    messagingSenderId: '163216286673',
    projectId: 'restuarantpager',
    authDomain: 'restuarantpager.firebaseapp.com',
    databaseURL: 'https://restuarantpager-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'restuarantpager.appspot.com',
  );
}
